# Site settings
title: Evangelist Collective
email: mjbrender@gmail.com
url: https://evangelistcollective.github.io
description: "We Are Developer Evangelists- and So Can You! exists to facilitate sharing information, resources and encouragement among the Developer Evangelist community."

# Contact form: comment the line below if you want to stick with the default PHP contact form
# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings -- these are titles of the section
footer:
  copyright: We Are Developer Evangelists
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: http://evangelistcollective.slack.com
  - title: github
    url: http://github.com/evangelistcollective
  - title: twitter
    url: https://twitter.com/pinkyswearing/lists/developer-evangelists


# Postal address (add as many lines as necessary)
address:
  - line: The closest airport to
  - line: San Francisco, CA (<a href="https://twitter.com/mary_grace">Mary</a>, <a href="https://twitter.com/karishannon">Shannon</a>)
  - line: Austin, TX (<a href="https://twitter.com/ashleymcnamara">Ashley</a>)
  - line: Portland, OR (<a href="https://twitter.com/meg_hartley">Meg</a>, <a href="https://twitter.com/mbbroberg">Matt</a>)
  - line: Boston, MA (<a href="https://twitter.com/jonasrosland">Jonas</a>)
  - line: New York, NY (<a href="https://twitter.com/pinkyswearing">Laura</a>)

# Credits content
credits: 'Our collective is an inclusive thought experiment started by Dave Josephsen. This site is build by <a href="https://twitter.com/mbbroberg">Matt Broberg</a> on Freelancer: a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# plugins
plugins:
  - jekyll-redirect-from
